name: Test project cases
run-name: ${{ github.actor }} is testing publish flow in github action
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  # job name
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://npm.pkg.github.com/
          scope: '@zwkang-dev'
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - run: pnpm test
